export const USER_LOGIN = {
  REQUEST: 'USER_LOGIN_REQUEST',
  SUCCESS: 'USER_LOGIN_SUCCESS',
  FAILED: 'USER_LOGIN_FAILED',
};

export const USER_REGISTER = {
  REQUEST: 'USER_REGISTER_REQUEST',
  SUCCESS: 'USER_REGISTER_SUCCESS',
  FAILED: 'USER_REGISTER_FAILED',
};

export const USER_LOGOUT = 'USER_LOGOUT';
