export const LOGOUT = 'LOGOUT';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const SET_USER = 'SET_USER';

export const CREATE_NOTIF = 'CREATE_NOTIF';
export const DELETE_NOTIF = 'DELETE_NOTIF';

export const SET_TOTAL_NOTIF = 'SET_TOTAL_NOTIF';
export const RESET_TOTAL_NOTIF = 'RESET_TOTAL_NOTIF';

export const PROUDCT_SUCCESS = 'PROUDCT_SUCCESS';
export const PRODUCT_FAILED = 'PROUDCT_FAILED';
